version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/examples/otel-example" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/examples/prom-example" # Location of package manifests
    schedule:
      interval: "weekly"
